const COLOR_DARK = "#282c34";
const COLOR_LIGHT = "#BDBDBD";
const COLOR_CARD = "#FFFFFF";
const COLOR_MED = "#ACF6EB";
const COLOR_PRIMARY = "#FF7900";
const SHADOW = "#F3F2F1";
const COLOR_FONT_LIGHT = "#C4C4C6";
const COLOR_FONT_NORMAL = "#79797A";
const COLOR_FONT_DARK = "#445582";

export {
  COLOR_DARK,
  COLOR_MED,
  COLOR_PRIMARY,
  SHADOW,
  COLOR_FONT_NORMAL,
  COLOR_FONT_DARK,
  COLOR_CARD,
  COLOR_FONT_LIGHT,
  COLOR_LIGHT,
};
